name : Postman Collection Workflow

on: 
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    -cron : 30 02 * * 1-5
    -cron : 00 14 * * 1-5 

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0

     - name: Install nodeJS
       uses: actions/setup-node@v3.9.1
       with:
        node-version: '22'

      -name: Install Newman and reporter
       run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

       -name: Run Collection
        run: |
             newman run 'Inwarranty-flow Collection.postman_collection.json'\
             -e QA.postman_environment.json\
             -d testdata.csv\
             -r htmlextra
             
    
